// vocab.js
const VOCAB_DATA = {
  "Essentials": {
    "Essentials": [
      { english: "Excuse me / Sorry", japanese: "すみません", romaji: "Sumimasen", pronunciation: "soo-mee-mah-sen" },
      { english: "Thank you very much", japanese: "ありがとうございます", romaji: "Arigatō gozaimasu", pronunciation: "ah-ree-gah-toh goh-zah-ee-mas" },
      { english: "This", japanese: "これ", romaji: "Kore", pronunciation: "koh-reh" },
      { english: "That (near you)", japanese: "それ", romaji: "Sore", pronunciation: "soh-reh" },
      { english: "Please (requesting an item)", japanese: "ください", romaji: "Kudasai", pronunciation: "koo-dah-sigh" },
      { english: "Please (general favor)", japanese: "お願いします", romaji: "Onegaishimasu", pronunciation: "oh-neh-guy-shee-mas" },
      { english: "No thank you / I'm good", japanese: "大丈夫です", romaji: "Daijōbu desu", pronunciation: "dye-joh-bu dess" },
      { english: "I am ~", japanese: "私は〜です", romaji: "Watashi wa ~ desu", pronunciation: "wah-tah-shee wah ~ dess" },
      { english: "I don’t understand", japanese: "わかりません", romaji: "Wakarimasen", pronunciation: "wah-kah-ree-mah-sen" }
    ],
    "Greetings": [
      { english: "Hello / Good afternoon", japanese: "こんにちは", romaji: "Konnichiwa", pronunciation: "kon-nee-chee-wah" },
      { english: "Good morning", japanese: "おはようございます", romaji: "Ohayō gozaimasu", pronunciation: "oh-hah-yoh goh-zah-ee-mas" },
      { english: "Good evening", japanese: "こんばんは", romaji: "Konbanwa", pronunciation: "kon-bahn-wah" },
      { english: "Good night", japanese: "おやすみ", romaji: "Oyasumi", pronunciation: "oh-yah-soo-mee" }
    ],
    "Restaurants": [
      { english: "Can I place an order?", japanese: "注文お願いします", romaji: "Chūmon onegaishimasu", pronunciation: "choo-mohn oh-neh-guy-shee-mas" },
      { english: "Water please", japanese: "水をお願いします", romaji: "Mizu o onegaishimasu", pronunciation: "mee-zoo oh oh-neh-guy-shee-mas" },
      { english: "Can I get the check / bill please", japanese: "お会計お願いします", romaji: "Okaikei onegaishimasu", pronunciation: "oh-kai-kay oh-neh-guy-shee-mas" }
    ]
  },
  "Core Travel Vocabulary": {
    "Restaurants": [
      { english: "Beer, one more", japanese: "ビールもう一杯", romaji: "Bīru mō ippai", pronunciation: "bee-roo moh ee-pie" },
      { english: "Reservation", japanese: "よやく", romaji: "Yoyaku", pronunciation: "yoh-yah-koo" }
    ],
    "Shopping": [
      { english: "Do you have (it)?", japanese: "ありますか", romaji: "Arimasu ka", pronunciation: "ah-ree-mas kah" },
      { english: "How much?", japanese: "いくら", romaji: "Ikura", pronunciation: "ee-koo-rah" },
      { english: "Please show me", japanese: "見せてください", romaji: "Misete kudasai", pronunciation: "mee-seh-teh koo-dah-sigh" }
    ],
    "Questions": [
      { english: "What is this?", japanese: "これは何ですか", romaji: "Kore wa nan desu ka", pronunciation: "koh-reh wah nahn dess kah" },
      { english: "What is your name?", japanese: "名前はなんですか", romaji: "Namae wa nan desu ka", pronunciation: "nah-mah-eh wah nahn dess kah" }
    ],
    "Directions": [
      { english: "Where is the bathroom?", japanese: "トイレはどこですか", romaji: "Toire wa doko desu ka", pronunciation: "toy-reh wah doh-koh dess kah" }
    ],
    "Communication": [
      { english: "I can’t speak Japanese", japanese: "日本語を話せません", romaji: "Nihongo o hanasemasen", pronunciation: "nee-hohn-goh oh hah-nah-seh-mah-sen" },
      { english: "I am practicing my Japanese", japanese: "私は日本語を練習しています。", romaji: "Watashi wa nihongo o renshū shite imasu", pronunciation: "wah-tah-shee wah nee-hohn-goh oh ren-shoo sheh-teh ee-mas" }
    ],
    "Hotel": [
      { english: "Reservation / appointment", japanese: "よやく", romaji: "Yoyaku", pronunciation: "yoh-yah-koo" }
    ],
    "Numbers": [
      { english: "Hundred", japanese: "ひゃく", romaji: "Hyaku", pronunciation: "hyah-koo" },
      { english: "Two hundred", japanese: "にひゃく", romaji: "Ni-hyaku", pronunciation: "nee-hyah-koo" },
      { english: "Three hundred", japanese: "さんびゃく", romaji: "San-byaku", pronunciation: "sahn-byah-koo" },
      { english: "Four hundred", japanese: "よんひゃく", romaji: "Yon-hyaku", pronunciation: "yohn-hyah-koo" },
      { english: "Six hundred", japanese: "ろっぴゃく", romaji: "Roppyaku", pronunciation: "roh-ppyah-koo" },
      { english: "Eight hundred", japanese: "はっぴゃく", romaji: "Happyaku", pronunciation: "hah-ppyah-koo" },
      { english: "Twenty", japanese: "にじゅう", romaji: "Ni-jū", pronunciation: "nee-joo" },
      { english: "Thirty", japanese: "さんじゅう", romaji: "San-jū", pronunciation: "sahn-joo" },
      { english: "Four thousand", japanese: "よんせん", romaji: "Yon-sen", pronunciation: "yohn-sen" },
      { english: "Three thousand", japanese: "さんぜん", romaji: "Sanzen", pronunciation: "sahn-zen" },
      { english: "Eight thousand", japanese: "はっせん", romaji: "Hassen", pronunciation: "hah-sen" }
    ],
    "Time & Dates": [
      { english: "From", japanese: "から", romaji: "Kara", pronunciation: "kah-rah" },
      { english: "Until / to", japanese: "まで", romaji: "Made", pronunciation: "mah-deh" },
      { english: "Morning / a.m.", japanese: "ごぜん", romaji: "Gozen", pronunciation: "goh-zen" },
      { english: "Afternoon / p.m.", japanese: "ごご", romaji: "Gogo", pronunciation: "goh-goh" }
    ]
  },
  "Basic Japanese Words": {
    "Key Phrases": [
      { english: "Yes", japanese: "はい", romaji: "Hai", pronunciation: "hai" },
      { english: "No", japanese: "いいえ", romaji: "Iie", pronunciation: "ee-eh" },
      { english: "What is your name?", japanese: "名前はなんですか", romaji: "Namae wa nan desu ka", pronunciation: "nah-mah-eh wah nahn dess kah" },
      { english: "I am ~", japanese: "私は〜です", romaji: "Watashi wa ~ desu", pronunciation: "wah-tah-shee wah dess" },
      { english: "I came from ~ / I am from ~", japanese: "〜から来ました", romaji: "~ kara kimashita", pronunciation: "kah-rah kee-mah-shee-tah" },
      { english: "What is this?", japanese: "これは何ですか", romaji: "Kore wa nan desu ka", pronunciation: "koh-reh wah nahn dess kah" },
      { english: "How much?", japanese: "いくらですか", romaji: "Ikura desu ka", pronunciation: "ee-koo-rah dess kah" },
      { english: "Can I get this one? / I'll take this one", japanese: "これください", romaji: "Kore kudasai", pronunciation: "koh-reh koo-dah-sigh" },
      { english: "Please", japanese: "おねがいします", romaji: "Onegaishimasu", pronunciation: "oh-neh-guy-shee-mas" },
      { english: "Can I place an order?", japanese: "注文お願いします", romaji: "Chūmon onegaishimasu", pronunciation: "choo-mohn oh-neh-guy-shee-mas" },
      { english: "Water please", japanese: "水をお願いします", romaji: "Mizu o onegaishimasu", pronunciation: "mee-zoo oh oh-neh-guy-shee-mas" },
      { english: "Can I get the check/bill?", japanese: "お会計お願いします", romaji: "Okaikei onegaishimasu", pronunciation: "oh-kai-kay oh-neh-guy-shee-mas" },
      { english: "Where am I?", japanese: "ここはどこですか", romaji: "Koko wa doko desu ka", pronunciation: "koh-koh wah doh-koh dess kah" },
      { english: "Where is the bathroom?", japanese: "トイレはどこですか", romaji: "Toire wa doko desu ka", pronunciation: "toy-reh wah doh-koh dess kah" },
      { english: "Where is the train station?", japanese: "駅はどこですか", romaji: "Eki wa doko desu ka", pronunciation: "eh-kee wah doh-koh dess kah" },
      { english: "What time is it now?", japanese: "今何時ですか", romaji: "Ima nan ji desu ka", pronunciation: "ee-mah nahn jee dess kah" },
      { english: "I don't understand", japanese: "わかりません", romaji: "Wakarimasen", pronunciation: "wah-kah-ree-mah-sen" },
      { english: "I can't speak Japanese", japanese: "日本語を話せません", romaji: "Nihongo o hanasemasen", pronunciation: "nee-hohn-goh oh hah-nah-seh-mah-sen" }
    ],
    "Greetings": [
      { english: "Good morning", japanese: "おはようございます", romaji: "Ohayō gozaimasu", pronunciation: "oh-hah-yoh goh-zah-ee-mas" },
      { english: "Good afternoon", japanese: "こんにちは", romaji: "Konnichiwa", pronunciation: "kon-nee-chee-wah" },
      { english: "Good evening", japanese: "こんばんは", romaji: "Konbanwa", pronunciation: "kon-bahn-wah" },
      { english: "Thank you", japanese: "ありがとうございます", romaji: "Arigatō gozaimasu", pronunciation: "ah-ree-gah-toh goh-zah-ee-mas" },
      { english: "Excuse me / I'm sorry", japanese: "すみません", romaji: "Sumimasen", pronunciation: "soo-mee-mah-sen" }
    ],
    "People & Pronouns": [
      { english: "I (watashi / boku / ore)", japanese: "私、僕、俺", romaji: "Watashi / Boku / Ore", pronunciation: "" },
      { english: "Friend", japanese: "友達", romaji: "Tomodachi", pronunciation: "toh-moh-dah-chee" },
      { english: "Co-worker", japanese: "同僚", romaji: "Dōryō", pronunciation: "doh-ryoh" },
      { english: "Boss / Company president", japanese: "部長、社長", romaji: "Buchō / Shachō", pronunciation: "boo-choh / shah-choh" },
      { english: "Family", japanese: "家族", romaji: "Kazoku", pronunciation: "kah-zoh-koo" },
      { english: "Father", japanese: "お父さん", romaji: "Otō-san", pronunciation: "oh-toh-san" },
      { english: "Mother", japanese: "お母さん", romaji: "Okā-san", pronunciation: "oh-kah-san" },
      { english: "Older brother", japanese: "お兄さん", romaji: "Onii-san", pronunciation: "oh-nee-san" },
      { english: "Older sister", japanese: "お姉さん", romaji: "Onee-san", pronunciation: "oh-neh-san" },
      { english: "Younger brother", japanese: "弟", romaji: "Otōto", pronunciation: "oh-toh-toh" },
      { english: "Younger sister", japanese: "妹", romaji: "Imōto", pronunciation: "ee-moh-toh" },
      { english: "Adults", japanese: "大人", romaji: "Otona", pronunciation: "oh-toh-nah" },
      { english: "Children", japanese: "子供", romaji: "Kodomo", pronunciation: "koh-doh-moh" },
      { english: "Boyfriend", japanese: "彼氏", romaji: "Kareshi", pronunciation: "kah-reh-shee" },
      { english: "Girlfriend", japanese: "彼女", romaji: "Kanojo", pronunciation: "kah-noh-joh" },
      { english: "Man", japanese: "男の人", romaji: "Otoko no hito", pronunciation: "oh-toh-koh noh hee-toh" },
      { english: "Woman", japanese: "女の人", romaji: "Onna no hito", pronunciation: "ohn-nah noh hee-toh" }
    ],
    "Food & Drink": [
      { english: "Breakfast", japanese: "朝ご飯", romaji: "Asa-gohan", pronunciation: "ah-sah goh-hahn" },
      { english: "Lunch", japanese: "昼ご飯", romaji: "Hiru-gohan", pronunciation: "hee-roo goh-hahn" },
      { english: "Dinner", japanese: "夜ご飯", romaji: "Yoru-gohan", pronunciation: "yoh-roo goh-hahn" },
      { english: "Rice / Meal", japanese: "ご飯", romaji: "Gohan", pronunciation: "goh-hahn" },
      { english: "Bread", japanese: "パン", romaji: "Pan", pronunciation: "pahn" },
      { english: "Meat", japanese: "肉", romaji: "Niku", pronunciation: "nee-koo" },
      { english: "Fish", japanese: "魚", romaji: "Sakana", pronunciation: "sah-kah-nah" },
      { english: "Vegetables", japanese: "野菜", romaji: "Yasai", pronunciation: "yah-sigh" },
      { english: "Fruits", japanese: "果物", romaji: "Kudamono", pronunciation: "koo-dah-moh-noh" },
      { english: "Soup", japanese: "スープ", romaji: "Sūpu", pronunciation: "soo-poo" },
      { english: "Salad", japanese: "サラダ", romaji: "Sarada", pronunciation: "sah-rah-dah" },
      { english: "Egg", japanese: "卵", romaji: "Tamago", pronunciation: "tah-mah-goh" },
      { english: "Milk", japanese: "牛乳", romaji: "Gyūnyū", pronunciation: "gyoo-nyoo" },
      { english: "Cheese", japanese: "チーズ", romaji: "Chīzu", pronunciation: "chee-zoo" },
      { english: "Dessert", japanese: "デザート", romaji: "Dezāto", pronunciation: "deh-zah-toh" },
      { english: "Water", japanese: "水", romaji: "Mizu", pronunciation: "mee-zoo" },
      { english: "Tea / Green tea", japanese: "お茶", romaji: "Ocha", pronunciation: "oh-chah" },
      { english: "Coffee", japanese: "コーヒー", romaji: "Kōhī", pronunciation: "koh-hee" },
      { english: "Alcohol / Sake", japanese: "お酒", romaji: "Osake", pronunciation: "oh-sah-keh" },
      { english: "Wine", japanese: "ワイン", romaji: "Wain", pronunciation: "wah-een" },
      { english: "Beer", japanese: "ビール", romaji: "Bīru", pronunciation: "bee-roo" }
    ],
    "Numbers": [
      { english: "1", japanese: "一", romaji: "ichi", pronunciation: "ee-chee" },
      { english: "2", japanese: "二", romaji: "ni", pronunciation: "nee" },
      { english: "3", japanese: "三", romaji: "san", pronunciation: "sahn" },
      { english: "4", japanese: "四", romaji: "yon", pronunciation: "yohn" },
      { english: "5", japanese: "五", romaji: "go", pronunciation: "goh" },
      { english: "6", japanese: "六", romaji: "roku", pronunciation: "roh-koo" },
      { english: "7", japanese: "七", romaji: "nana", pronunciation: "nah-nah" },
      { english: "8", japanese: "八", romaji: "hachi", pronunciation: "hah-chee" },
      { english: "9", japanese: "九", romaji: "kyū", pronunciation: "kyoo" },
      { english: "10", japanese: "十", romaji: "jū", pronunciation: "joo" },
      { english: "11", japanese: "十一", romaji: "jūichi", pronunciation: "joo-ee-chee" },
      { english: "12", japanese: "十二", romaji: "jūni", pronunciation: "joo-nee" },
      { english: "20", japanese: "二十", romaji: "nijū", pronunciation: "nee-joo" },
      { english: "21", japanese: "二十一", romaji: "nijūichi", pronunciation: "nee-joo-ee-chee" },
      { english: "30", japanese: "三十", romaji: "sanjū", pronunciation: "sahn-joo" },
      { english: "32", japanese: "三十二", romaji: "sanjūni", pronunciation: "sahn-joo-nee" },
      { english: "40", japanese: "四十", romaji: "yonjū", pronunciation: "yohn-joo" },
      { english: "43", japanese: "四十三", romaji: "yonjūsan", pronunciation: "yohn-joo-sahn" },
      { english: "50", japanese: "五十", romaji: "gojū", pronunciation: "goh-joo" },
      { english: "54", japanese: "五十四", romaji: "gojūyon", pronunciation: "goh-joo-yohn" },
      { english: "60", japanese: "六十", romaji: "rokujū", pronunciation: "roh-koo-joo" },
      { english: "65", japanese: "六十五", romaji: "rokujūgo", pronunciation: "roh-koo-joo-goh" },
      { english: "70", japanese: "七十", romaji: "nanajū", pronunciation: "nah-nah-joo" },
      { english: "76", japanese: "七十六", romaji: "nanajūroku", pronunciation: "nah-nah-joo-roh-koo" },
      { english: "80", japanese: "八十", romaji: "hachijū", pronunciation: "hah-chee-joo" },
      { english: "87", japanese: "八十七", romaji: "hachijūnana", pronunciation: "hah-chee-joo-nah-nah" },
      { english: "90", japanese: "九十", romaji: "kyūjū", pronunciation: "kyoo-joo" },
      { english: "98", japanese: "九十八", romaji: "kyūjūhachi", pronunciation: "kyoo-joo-hah-chee" },
      { english: "100", japanese: "百", romaji: "hyaku", pronunciation: "hyah-koo" },
      { english: "1000", japanese: "千", romaji: "sen", pronunciation: "sen" },
      { english: "2000", japanese: "二千", romaji: "nisen", pronunciation: "nee-sen" },
      { english: "3000", japanese: "三千", romaji: "sanzen", pronunciation: "sahn-zen" },
      { english: "5000", japanese: "五千", romaji: "gosen", pronunciation: "goh-sen" }
    ],
    "Time & Dates": [
      { english: "Sunday", japanese: "日曜日", romaji: "Nichiyōbi", pronunciation: "nee-chee-yoh-bee" },
      { english: "Monday", japanese: "月曜日", romaji: "Getsuyōbi", pronunciation: "geh-tsoo-yoh-bee" },
      { english: "Tuesday", japanese: "火曜日", romaji: "Kayōbi", pronunciation: "kah-yoh-bee" },
      { english: "Wednesday", japanese: "水曜日", romaji: "Suiyōbi", pronunciation: "soo-ee-yoh-bee" },
      { english: "Thursday", japanese: "木曜日", romaji: "Mokuyōbi", pronunciation: "moh-koo-yoh-bee" },
      { english: "Friday", japanese: "金曜日", romaji: "Kinyōbi", pronunciation: "keen-yoh-bee" },
      { english: "Saturday", japanese: "土曜日", romaji: "Doyōbi", pronunciation: "doh-yoh-bee" },
      { english: "January", japanese: "一月", romaji: "Ichigatsu", pronunciation: "ee-chee-gah-tsoo" },
      { english: "February", japanese: "二月", romaji: "Nigatsu", pronunciation: "nee-gah-tsoo" },
      { english: "March", japanese: "三月", romaji: "Sangatsu", pronunciation: "sahn-gah-tsoo" },
      { english: "April", japanese: "四月", romaji: "Shigatsu", pronunciation: "shee-gah-tsoo" },
      { english: "May", japanese: "五月", romaji: "Gogatsu", pronunciation: "goh-gah-tsoo" },
      { english: "June", japanese: "六月", romaji: "Rokugatsu", pronunciation: "roh-koo-gah-tsoo" },
      { english: "July", japanese: "七月", romaji: "Shichigatsu", pronunciation: "shee-chee-gah-tsoo" },
      { english: "August", japanese: "八月", romaji: "Hachigatsu", pronunciation: "hah-chee-gah-tsoo" },
      { english: "September", japanese: "九月", romaji: "Kugatsu", pronunciation: "koo-gah-tsoo" },
      { english: "October", japanese: "十月", romaji: "Jūgatsu", pronunciation: "joo-gah-tsoo" },
      { english: "November", japanese: "十一月", romaji: "Jūichigatsu", pronunciation: "joo-ee-chee-gah-tsoo" },
      { english: "December", japanese: "十二月", romaji: "Jūnigatsu", pronunciation: "joo-nee-gah-tsoo" },
      { english: "Today", japanese: "今日", romaji: "Kyō", pronunciation: "kyoh" },
      { english: "Yesterday", japanese: "昨日", romaji: "Kinō", pronunciation: "kee-noh" },
      { english: "Tomorrow", japanese: "明日", romaji: "Ashita", pronunciation: "ah-shee-tah" },
      { english: "This week", japanese: "今週", romaji: "Konshū", pronunciation: "kohn-shoo" },
      { english: "Last week", japanese: "先週", romaji: "Senshū", pronunciation: "sen-shoo" },
      { english: "Next week", japanese: "来週", romaji: "Raishū", pronunciation: "rye-shoo" },
      { english: "This month", japanese: "今月", romaji: "Kongetsu", pronunciation: "kohn-geh-tsoo" },
      { english: "Last month", japanese: "先月", romaji: "Sengetsu", pronunciation: "sen-geh-tsoo" },
      { english: "Next month", japanese: "来月", romaji: "Raigetsu", pronunciation: "rye-gee-tsoo" },
      { english: "This year", japanese: "今年", romaji: "Kotoshi", pronunciation: "koh-toh-shee" },
      { english: "Last year", japanese: "去年", romaji: "Kyonen", pronunciation: "kyoh-nen" },
      { english: "Next year", japanese: "来年", romaji: "Rainen", pronunciation: "rye-nen" },
      { english: "1 o'clock", japanese: "一時", romaji: "ichi-ji", pronunciation: "ichi-ji" },
      { english: "2 o'clock", japanese: "二時", romaji: "ni-ji", pronunciation: "ni-ji" },
      { english: "3 o'clock", japanese: "三時", romaji: "san-ji", pronunciation: "san-ji" },
      { english: "4 o'clock", japanese: "四時", romaji: "yon-ji", pronunciation: "yon-ji" },
      { english: "5 o'clock", japanese: "五時", romaji: "go-ji", pronunciation: "go-ji" },
      { english: "6 o'clock", japanese: "六時", romaji: "roku-ji", pronunciation: "roku-ji" },
      { english: "7 o'clock", japanese: "七時", romaji: "nana-ji", pronunciation: "nana-ji" },
      { english: "8 o'clock", japanese: "八時", romaji: "hachi-ji", pronunciation: "hachi-ji" },
      { english: "9 o'clock", japanese: "九時", romaji: "ku-ji", pronunciation: "ku-ji" },
      { english: "10 o'clock", japanese: "十時", romaji: "juu-ji", pronunciation: "juu-ji" },
      { english: "11 o'clock", japanese: "十一時", romaji: "juu-ichi-ji", pronunciation: "juu-ichi-ji" },
      { english: "12 o'clock", japanese: "十二時", romaji: "juu-ni-ji", pronunciation: "juu-ni-ji" }
    ],
    "Places": [
      { english: "Station", japanese: "駅", romaji: "Eki", pronunciation: "eh-kee" },
      { english: "Hospital", japanese: "病院", romaji: "Byōin", pronunciation: "byoh-een" },
      { english: "Money exchange", japanese: "両替", romaji: "Ryōgae", pronunciation: "ryoh-guy" },
      { english: "Bank", japanese: "銀行", romaji: "Ginkō", pronunciation: "geen-koh" },
      { english: "Police station", japanese: "警察署", romaji: "Keisatsusho", pronunciation: "kay-sah-tsoo-shoh" },
      { english: "Post office", japanese: "郵便局", romaji: "Yūbinkyoku", pronunciation: "yoo-been-kyoh-koo" },
      { english: "Convenience store", japanese: "コンビニ", romaji: "Konbini", pronunciation: "kohn-bee-nee" },
      { english: "Bakery", japanese: "パン屋", romaji: "Pan-ya", pronunciation: "pahn-yah" },
      { english: "Store / Shop", japanese: "店", romaji: "Mise", pronunciation: "mee-seh" },
      { english: "Supermarket", japanese: "スーパー", romaji: "Sūpā", pronunciation: "soo-pah" },
      { english: "Airport", japanese: "空港", romaji: "Kūkō", pronunciation: "koo-koh" },
      { english: "Bus stop", japanese: "バス停", romaji: "Basutei", pronunciation: "bah-soo-tay" },
      { english: "Port", japanese: "港", romaji: "Minato", pronunciation: "mee-nah-toh" },
      { english: "Shrine", japanese: "神社", romaji: "Jinja", pronunciation: "jeen-jah" },
      { english: "Temple", japanese: "お寺", romaji: "Otera", pronunciation: "oh-teh-rah" },
      { english: "Town", japanese: "町", romaji: "Machi", pronunciation: "mah-chee" },
      { english: "Hotel", japanese: "ホテル", romaji: "Hoteru", pronunciation: "hoh-teh-roo" },
      { english: "Reception", japanese: "受付", romaji: "Uketsuke", pronunciation: "oo-keh-tsoo-keh" }
    ],
    "Colors": [
      { english: "Red", japanese: "赤", romaji: "Aka", pronunciation: "ah-kah" },
      { english: "Blue", japanese: "青", romaji: "Ao", pronunciation: "ah-oh" },
      { english: "Yellow", japanese: "黄色", romaji: "Kiiro", pronunciation: "kee-ee-roh" },
      { english: "Green", japanese: "緑", romaji: "Midori", pronunciation: "mee-doh-ree" },
      { english: "White", japanese: "白", romaji: "Shiro", pronunciation: "shee-roh" },
      { english: "Black", japanese: "黒", romaji: "Kuro", pronunciation: "koo-roh" },
      { english: "Purple", japanese: "紫", romaji: "Murasaki", pronunciation: "moo-rah-sah-kee" },
      { english: "Orange", japanese: "オレンジ", romaji: "Orenji", pronunciation: "oh-ren-jee" },
      { english: "Pink", japanese: "ピンク", romaji: "Pinku", pronunciation: "peen-koo" },
      { english: "Brown", japanese: "茶色", romaji: "Chairo", pronunciation: "chah-ee-roh" }
    ],
    "Essential Verbs": [
      { english: "to eat", japanese: "食べる", romaji: "Taberu", pronunciation: "tah-beh-roo" },
      { english: "to go", japanese: "行く", romaji: "Iku", pronunciation: "ee-koo" },
      { english: "to drink", japanese: "飲む", romaji: "Nomu", pronunciation: "noh-moo" },
      { english: "to listen / hear", japanese: "聞く", romaji: "Kiku", pronunciation: "kee-koo" },
      { english: "to read", japanese: "読む", romaji: "Yomu", pronunciation: "yoh-moo" },
      { english: "to see / look / watch", japanese: "見る", romaji: "Miru", pronunciation: "mee-roo" },
      { english: "to sleep", japanese: "寝る", romaji: "Neru", pronunciation: "neh-roo" },
      { english: "to wake up", japanese: "起きる", romaji: "Okiru", pronunciation: "oh-kee-roo" },
      { english: "to speak / talk", japanese: "話す", romaji: "Hanasu", pronunciation: "hah-nah-soo" },
      { english: "to return / go back", japanese: "帰る", romaji: "Kaeru", pronunciation: "kah-eh-roo" },
      { english: "to sit down", japanese: "座る", romaji: "Suwaru", pronunciation: "soo-wah-roo" },
      { english: "to stand up", japanese: "立つ", romaji: "Tatsu", pronunciation: "tah-tsoo" },
      { english: "to swim", japanese: "泳ぐ", romaji: "Oyogu", pronunciation: "oh-yoh-goo" },
      { english: "to play", japanese: "遊ぶ", romaji: "Asobu", pronunciation: "ah-soh-boo" },
      { english: "to ride", japanese: "乗る", romaji: "Noru", pronunciation: "noh-roo" },
      { english: "to buy", japanese: "買う", romaji: "Kau", pronunciation: "kah-oo" },
      { english: "to meet", japanese: "会う", romaji: "Au", pronunciation: "ah-oo" },
      { english: "to write", japanese: "書く", romaji: "Kaku", pronunciation: "kah-koo" },
      { english: "to wait", japanese: "待つ", romaji: "Matsu", pronunciation: "mah-tsoo" },
      { english: "to take a picture", japanese: "撮る", romaji: "Toru", pronunciation: "toh-roo" }
    ]
  }
};

const HIRAGANA_DATA = [
  ["あ","a","ah"],["い","i","ee"],["う","u","oo"],["え","e","eh"],["お","o","oh"],
  ["か","ka","kah"],["き","ki","kee"],["く","ku","koo"],["け","ke","keh"],["こ","ko","koh"],
  ["さ","sa","sah"],["し","shi","shee"],["す","su","soo"],["せ","se","seh"],["そ","so","soh"],
  ["た","ta","tah"],["ち","chi","chee"],["つ","tsu","tsoo"],["て","te","teh"],["と","to","toh"],
  ["な","na","nah"],["に","ni","nee"],["ぬ","nu","noo"],["ね","ne","neh"],["の","no","noh"],
  ["は","ha","hah"],["ひ","hi","hee"],["ふ","fu","foo"],["へ","he","heh"],["ほ","ho","hoh"],
  ["ま","ma","mah"],["み","mi","mee"],["む","mu","moo"],["め","me","meh"],["も","mo","moh"],
  ["や","ya","yah"],["ゆ","yu","yoo"],["よ","yo","yoh"],
  ["ら","ra","rah"],["り","ri","ree"],["る","ru","roo"],["れ","re","reh"],["ろ","ro","roh"],
  ["わ","wa","wah"],["を","wo (o)","woh"],["ん","n","n"]
];

const KATAKANA_DATA = [
  ["ア","a","ah"],["イ","i","ee"],["ウ","u","oo"],["エ","e","eh"],["オ","o","oh"],
  ["カ","ka","kah"],["キ","ki","kee"],["ク","ku","koo"],["ケ","ke","keh"],["コ","ko","koh"],
  ["サ","sa","sah"],["シ","shi","shee"],["ス","su","soo"],["セ","se","seh"],["ソ","so","soh"],
  ["タ","ta","tah"],["チ","chi","chee"],["ツ","tsu","tsoo"],["テ","te","teh"],["ト","to","toh"],
  ["ナ","na","nah"],["ニ","ni","nee"],["ヌ","nu","noo"],["ネ","ne","neh"],["ノ","no","noh"],
  ["ハ","ha","hah"],["ヒ","hi","hee"],["フ","fu","foo"],["ヘ","he","heh"],["ホ","ho","hoh"],
  ["マ","ma","mah"],["ミ","mi","mee"],["ム","mu","moo"],["メ","me","meh"],["モ","mo","moh"],
  ["ヤ","ya","yah"],["ユ","yu","yoo"],["ヨ","yo","yoh"],
  ["ラ","ra","rah"],["リ","ri","ree"],["ル","ru","roo"],["レ","re","reh"],["ロ","ro","roh"],
  ["ワ","wa","wah"],["ヲ","wo (o)","woh"],["ン","n","n"]
];